export enum UserActionType {
    FETCH_USERS = 'FETCH_USERS',
    SET_USERS = 'SET_USERS',
    FETCH_CREATE_USER = 'FETCH_CREATE_USER',
    CREATE_USER = 'CREATE_USER',
    FETCH_REMOVE_USER = 'FETCH_REMOVE_USER',
    REMOVE_USER = 'REMOVE_USER',
    SET_USER_ERROR = 'SET_USER_ERROR'
}