export enum UserDetailsActionType {
    FETCH_USER_DETAILS = 'FETCH_USER_DETAILS',
    SET_USER_DETAILS = 'SET_USER_DETAILS',
    SET_USER_DETAILS_ERROR = 'SET_USER_DETAILS_ERROR',
    FETCH_UPDATE_USER_DETAILS='FETCH_UPDATE_USER_DETAILS',
    UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS'
}